version: '3.9'

services:
    mongo:
        image: mongo
        restart: always
        ports:
            - 27021:27021
        env_file:
            - .env

    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        env_file:
            - .env
        depends_on:
            - mongo

    backend:
        build:
            context: ./
            dockerfile: ./Dockerfile
        restart: always
        ports:
            - 5000:5000
        volumes:
            - ./src:/app/src
        depends_on:
            - mongo

volumes:
    mongo:
    nodemodules:
